#!/bin/bash

_options=""
if [ "$#" -ge "1" ]
then
	_options="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
	shift
fi

mkdir -p /var/log/remote

reset
java $_options -jar target/cli-0.1-SNAPSHOT-shaded.jar -NodeId $(./remote-get-nodeid) -AmazonAccessKeyId $(cat amazon.access.key.secret) -AmazonSecretAccessKey $(cat amazon.secret.access.key.secret)
