#!/bin/bash

mkdir -p /var/log/remote

reset
java $_options -jar target/cli-0.1-SNAPSHOT-shaded.jar -OperatingMode Read -NodeId $(./remote-get-nodeid) -AmazonAccessKeyId $(cat amazon.access.key.secret) -AmazonSecretAccessKey $(cat amazon.secret.access.key.secret)